/* subcensus_scene_config.h — the scene list (X-macro). One ADD_SCENE per scene. */
ADD_SCENE(subcensus, start, Start)
ADD_SCENE(subcensus, settings, Settings)
ADD_SCENE(subcensus, places, Places)
ADD_SCENE(subcensus, place_actions, PlaceActions)
ADD_SCENE(subcensus, place_text, PlaceText)
ADD_SCENE(subcensus, confirm_delete, ConfirmDelete)
ADD_SCENE(subcensus, camp_picker, CampPicker)
ADD_SCENE(subcensus, camp, Camp)
ADD_SCENE(subcensus, sweep, Sweep)
ADD_SCENE(subcensus, recon_run, ReconRun)
ADD_SCENE(subcensus, recon, Recon)
ADD_SCENE(subcensus, recon_results, ReconResults)
ADD_SCENE(subcensus, review, Review)
ADD_SCENE(subcensus, review_detail, ReviewDetail)
ADD_SCENE(subcensus, review_label, ReviewLabel)
ADD_SCENE(subcensus, about, About)
ADD_SCENE(subcensus, todo, Todo)
