# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flippermin.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'flippermin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gui_pb2 as gui__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x66lippermin.proto\x12\x02PB\x1a\tgui.proto\"\xdf\x02\n\x04Main\x12\x12\n\ncommand_id\x18\x01 \x01(\r\x12\x16\n\x0e\x63ommand_status\x18\x02 \x01(\r\x12\x10\n\x08has_next\x18\x03 \x01(\x08\x12K\n\x1fgui_start_screen_stream_request\x18\x14 \x01(\x0b\x32 .PB_Gui.StartScreenStreamRequestH\x00\x12I\n\x1egui_stop_screen_stream_request\x18\x15 \x01(\x0b\x32\x1f.PB_Gui.StopScreenStreamRequestH\x00\x12/\n\x10gui_screen_frame\x18\x16 \x01(\x0b\x32\x13.PB_Gui.ScreenFrameH\x00\x12\x45\n\x1cgui_send_input_event_request\x18\x17 \x01(\x0b\x32\x1d.PB_Gui.SendInputEventRequestH\x00\x42\t\n\x07\x63ontentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flippermin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MAIN']._serialized_start=36
  _globals['_MAIN']._serialized_end=387
# @@protoc_insertion_point(module_scope)
